/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BarberRouteImport } from './routes/barber'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCalendarRouteImport } from './routes/admin/calendar'
import { Route as AdminCrmRouteImport } from './routes/admin/crm'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminServicesRouteImport } from './routes/admin/services'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminStaffRouteImport } from './routes/admin/staff'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin/subscriptions'
import { Route as BarberAgendaRouteImport } from './routes/barber/agenda'
import { Route as BarberClientesRouteImport } from './routes/barber/clientes'
import { Route as BarberFotosRouteImport } from './routes/barber/fotos'
import { Route as BarberPerfilRouteImport } from './routes/barber/perfil'
import { Route as ApiPublicAsaasWebhookRouteImport } from './routes/api/public/asaas-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BarberRoute = BarberRouteImport.update({
  id: '/barber',
  path: '/barber',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCrmRoute = AdminCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const BarberAgendaRoute = BarberAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => BarberRoute,
} as any)
const BarberClientesRoute = BarberClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => BarberRoute,
} as any)
const BarberFotosRoute = BarberFotosRouteImport.update({
  id: '/fotos',
  path: '/fotos',
  getParentRoute: () => BarberRoute,
} as any)
const BarberPerfilRoute = BarberPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => BarberRoute,
} as any)
const ApiPublicAsaasWebhookRoute = ApiPublicAsaasWebhookRouteImport.update({
  id: '/api/public/asaas-webhook',
  path: '/api/public/asaas-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/barber': typeof BarberRouteWithChildren
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/crm': typeof AdminCrmRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/barber/agenda': typeof BarberAgendaRoute
  '/barber/clientes': typeof BarberClientesRoute
  '/barber/fotos': typeof BarberFotosRoute
  '/barber/perfil': typeof BarberPerfilRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/barber': typeof BarberRouteWithChildren
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/crm': typeof AdminCrmRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/barber/agenda': typeof BarberAgendaRoute
  '/barber/clientes': typeof BarberClientesRoute
  '/barber/fotos': typeof BarberFotosRoute
  '/barber/perfil': typeof BarberPerfilRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/barber': typeof BarberRouteWithChildren
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/crm': typeof AdminCrmRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/barber/agenda': typeof BarberAgendaRoute
  '/barber/clientes': typeof BarberClientesRoute
  '/barber/fotos': typeof BarberFotosRoute
  '/barber/perfil': typeof BarberPerfilRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/barber'
    | '/login'
    | '/membership'
    | '/services'
    | '/shop'
    | '/admin/calendar'
    | '/admin/crm'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/subscriptions'
    | '/barber/agenda'
    | '/barber/clientes'
    | '/barber/fotos'
    | '/barber/perfil'
    | '/admin/'
    | '/api/public/asaas-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/barber'
    | '/login'
    | '/membership'
    | '/services'
    | '/shop'
    | '/admin/calendar'
    | '/admin/crm'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/subscriptions'
    | '/barber/agenda'
    | '/barber/clientes'
    | '/barber/fotos'
    | '/barber/perfil'
    | '/admin'
    | '/api/public/asaas-webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/barber'
    | '/login'
    | '/membership'
    | '/services'
    | '/shop'
    | '/admin/calendar'
    | '/admin/crm'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/subscriptions'
    | '/barber/agenda'
    | '/barber/clientes'
    | '/barber/fotos'
    | '/barber/perfil'
    | '/admin/'
    | '/api/public/asaas-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BarberRoute: typeof BarberRouteWithChildren
  LoginRoute: typeof LoginRoute
  MembershipRoute: typeof MembershipRoute
  ServicesRoute: typeof ServicesRoute
  ShopRoute: typeof ShopRoute
  ApiPublicAsaasWebhookRoute: typeof ApiPublicAsaasWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barber': {
      id: '/barber'
      path: '/barber'
      fullPath: '/barber'
      preLoaderRoute: typeof BarberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/crm': {
      id: '/admin/crm'
      path: '/crm'
      fullPath: '/admin/crm'
      preLoaderRoute: typeof AdminCrmRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/barber/agenda': {
      id: '/barber/agenda'
      path: '/agenda'
      fullPath: '/barber/agenda'
      preLoaderRoute: typeof BarberAgendaRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/clientes': {
      id: '/barber/clientes'
      path: '/clientes'
      fullPath: '/barber/clientes'
      preLoaderRoute: typeof BarberClientesRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/fotos': {
      id: '/barber/fotos'
      path: '/fotos'
      fullPath: '/barber/fotos'
      preLoaderRoute: typeof BarberFotosRouteImport
      parentRoute: typeof BarberRoute
    }
    '/barber/perfil': {
      id: '/barber/perfil'
      path: '/perfil'
      fullPath: '/barber/perfil'
      preLoaderRoute: typeof BarberPerfilRouteImport
      parentRoute: typeof BarberRoute
    }
    '/api/public/asaas-webhook': {
      id: '/api/public/asaas-webhook'
      path: '/api/public/asaas-webhook'
      fullPath: '/api/public/asaas-webhook'
      preLoaderRoute: typeof ApiPublicAsaasWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminCrmRoute: typeof AdminCrmRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCalendarRoute: AdminCalendarRoute,
  AdminCrmRoute: AdminCrmRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BarberRouteChildren {
  BarberAgendaRoute: typeof BarberAgendaRoute
  BarberClientesRoute: typeof BarberClientesRoute
  BarberFotosRoute: typeof BarberFotosRoute
  BarberPerfilRoute: typeof BarberPerfilRoute
}

const BarberRouteChildren: BarberRouteChildren = {
  BarberAgendaRoute: BarberAgendaRoute,
  BarberClientesRoute: BarberClientesRoute,
  BarberFotosRoute: BarberFotosRoute,
  BarberPerfilRoute: BarberPerfilRoute,
}

const BarberRouteWithChildren =
  BarberRoute._addFileChildren(BarberRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BarberRoute: BarberRouteWithChildren,
  LoginRoute: LoginRoute,
  MembershipRoute: MembershipRoute,
  ServicesRoute: ServicesRoute,
  ShopRoute: ShopRoute,
  ApiPublicAsaasWebhookRoute: ApiPublicAsaasWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
