-- Create a fresh admin user
INSERT INTO auth.users (
  instance_id,
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  recovery_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  created_at,
  updated_at,
  confirmation_token,
  email_change,
  email_change_token_new,
  recovery_token
) VALUES (
  '00000000-0000-0000-0000-000000000000',
  gen_random_uuid(),
  'authenticated',
  'authenticated',
  'admin@theroyalcut.com',
  crypt('RoyalAdmin2026!', gen_salt('bf')),
  now(),
  now(),
  now(),
  '{"role": "admin"}'::jsonb,
  '{"full_name": "Admin Master"}'::jsonb,
  now(),
  now(),
  '',
  '',
  '',
  ''
) RETURNING id;
